// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm8m5FTV4QRa7nBeLnv9O7kneU7B9TqIU',
    appId: '1:692054854713:web:242b03e53ef12e000ed1e8',
    messagingSenderId: '692054854713',
    projectId: 'flickpicks-cf5d5',
    authDomain: 'flickpicks-cf5d5.firebaseapp.com',
    databaseURL: 'https://flickpicks-cf5d5-default-rtdb.firebaseio.com',
    storageBucket: 'flickpicks-cf5d5.appspot.com',
    measurementId: 'G-2SDXJWZ2W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBehANIjPHCgZyKe0Cx_7lixC8M56vOWHY',
    appId: '1:692054854713:android:e46a1fbe91056e7d0ed1e8',
    messagingSenderId: '692054854713',
    projectId: 'flickpicks-cf5d5',
    databaseURL: 'https://flickpicks-cf5d5-default-rtdb.firebaseio.com',
    storageBucket: 'flickpicks-cf5d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7i2NkJRJi_v_uaZRu4ArlNoPd7XgijLQ',
    appId: '1:692054854713:ios:93a8aa71bd0248e00ed1e8',
    messagingSenderId: '692054854713',
    projectId: 'flickpicks-cf5d5',
    databaseURL: 'https://flickpicks-cf5d5-default-rtdb.firebaseio.com',
    storageBucket: 'flickpicks-cf5d5.appspot.com',
    iosBundleId: 'com.example.flickpicks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7i2NkJRJi_v_uaZRu4ArlNoPd7XgijLQ',
    appId: '1:692054854713:ios:81d2dad4928c79710ed1e8',
    messagingSenderId: '692054854713',
    projectId: 'flickpicks-cf5d5',
    databaseURL: 'https://flickpicks-cf5d5-default-rtdb.firebaseio.com',
    storageBucket: 'flickpicks-cf5d5.appspot.com',
    iosBundleId: 'com.example.flickpicks.RunnerTests',
  );
}
